/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

import clases.Estacion;
import clases.Color;

import java.util.ArrayList;

/**
 *
 * @author PGC
 */
public class FrmComboBox extends javax.swing.JFrame {

    ArrayList<String> opcionesList;
    ArrayList<Color> colores;

    public FrmComboBox() {
        initComponents();

        cargarComboEnum();

        opcionesList = new ArrayList<>();
        colores = new ArrayList<>();

        //Carga algunos colores en la lista
        colores.add(new Color("Rojo", 215, 34, 75));
        colores.add(new Color("Cyan", 89, 194, 187));
        colores.add(new Color("Amarillo", 247, 228, 105));
        colores.add(new Color("Azul", 44, 123, 192));

        cargarComboColores();
        this.cboColoresActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboOpcionesFijas = new javax.swing.JComboBox<>();
        btnOpcionesFijas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboOpcionesEnum = new javax.swing.JComboBox<>();
        btnOpcionesEnum = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOpcionesList = new javax.swing.JTextField();
        btnAgregarList = new javax.swing.JButton();
        cboOpcionesList = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnCargarList = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cboColores = new javax.swing.JComboBox<>();
        lblColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Opciones Fijas: ");

        cboOpcionesFijas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Matemática de Ingeniería", "Introducción a la Física", "Lenguaje de Programación", "Arquitectura y Organización de Computadores", "Base de Datos", "Inglés III" }));

        btnOpcionesFijas.setText("Ver");
        btnOpcionesFijas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesFijasActionPerformed(evt);
            }
        });

        jLabel2.setText("Opciones Enum:");

        btnOpcionesEnum.setText("Ver");
        btnOpcionesEnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesEnumActionPerformed(evt);
            }
        });

        jLabel3.setText("Opciones ArrayList:");

        btnAgregarList.setText("Agregar");
        btnAgregarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListActionPerformed(evt);
            }
        });

        btnCargarList.setText("Cargar");
        btnCargarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarListActionPerformed(evt);
            }
        });

        jLabel4.setText("Color");

        cboColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboColoresActionPerformed(evt);
            }
        });

        lblColor.setBackground(java.awt.SystemColor.control);
        lblColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboOpcionesFijas, 0, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOpcionesFijas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cboOpcionesEnum, 0, 289, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOpcionesEnum))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboOpcionesList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtOpcionesList, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarList)
                            .addComponent(btnCargarList))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboOpcionesFijas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpcionesFijas)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboOpcionesEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpcionesEnum))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpcionesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarList)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboOpcionesList, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnCargarList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionesFijasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesFijasActionPerformed

        if (cboOpcionesFijas.getSelectedIndex() == 0) {  //Nada seleccionado
            JOptionPane.showMessageDialog(rootPane,
                    "Selecciona una asignatura",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String asignatura = cboOpcionesFijas.getSelectedItem().toString();
            JOptionPane.showMessageDialog(rootPane,
                    "Asignatura: \n" + asignatura,
                    "Selector de Asignaturas",
                    JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnOpcionesFijasActionPerformed

    private void btnOpcionesEnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesEnumActionPerformed
        String mensaje = "";

        if (this.cboOpcionesEnum.getSelectedIndex() != 0) {
            Estacion seleccionada = (Estacion) this.cboOpcionesEnum.getSelectedItem();

            switch (seleccionada) {
                case OTOÑO:
                    mensaje = "Del 21 de marzo al 21 de junio";
                    break;
                case INVIERNO:
                    mensaje = "Del 21 de junio al 21 de septiembre";
                    break;
                case PRIMAVERA:
                    mensaje = "Del 21 de septiembre al 21 de diciembre";
                    break;
                case VERANO:
                    mensaje = "Del 21 de diciembre al 21 de marzo";
                    break;
            }

            JOptionPane.showMessageDialog(rootPane,
                    seleccionada + "\n" + mensaje,
                    "Estaciones del Año",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnOpcionesEnumActionPerformed

    private void btnAgregarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListActionPerformed
        String opcion = this.txtOpcionesList.getText();

        opcionesList.add(opcion);

        txtOpcionesList.setText("");
    }//GEN-LAST:event_btnAgregarListActionPerformed

    private void btnCargarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarListActionPerformed
        cargarComboList();
    }//GEN-LAST:event_btnCargarListActionPerformed

    private void cboColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboColoresActionPerformed
        Color color = (Color) cboColores.getSelectedItem();
        
        lblColor.setBackground( new java.awt.Color(color.r,color.g, color.b));

    }//GEN-LAST:event_cboColoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarList;
    private javax.swing.JButton btnCargarList;
    private javax.swing.JButton btnOpcionesEnum;
    private javax.swing.JButton btnOpcionesFijas;
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JComboBox<String> cboOpcionesEnum;
    private javax.swing.JComboBox<String> cboOpcionesFijas;
    private javax.swing.JComboBox<String> cboOpcionesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JTextField txtOpcionesList;
    // End of variables declaration//GEN-END:variables

    private void cargarComboEnum() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(Estacion.values());
        model.insertElementAt("SELECCIONA", 0);
        this.cboOpcionesEnum.setModel(model);
        this.cboOpcionesEnum.setSelectedIndex(0);
    }

    private void cargarComboList() {
        this.cboOpcionesList.setModel(new DefaultComboBoxModel(this.opcionesList.toArray()));
    }

    private void cargarComboColores() {
        this.cboColores.setModel(new DefaultComboBoxModel(colores.toArray()));

    }
}
